-- Created by Benjamin McDonnough
USE PizzaDB;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS pizza_discount;
DROP TABLE IF EXISTS order_discount;
DROP TABLE IF EXISTS pizza_topping;
DROP TABLE IF EXISTS dinein;
DROP TABLE IF EXISTS pickup;
DROP TABLE IF EXISTS delivery;
DROP TABLE IF EXISTS pizza;
DROP TABLE IF EXISTS ordertable;
DROP TABLE IF EXISTS discount;
DROP TABLE IF EXISTS topping;
DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS basesprice;

SET FOREIGN_KEY_CHECKS = 1;
